import { Montserrat, Oswald  } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Script from "next/script";
import SmoothScroll from "@/components/SmoothScroll";
//import GSAPAnimations from "@/components/GSAPAnimations";
import localFont from "next/font/local";

import "@/public/css/icomoon.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


const mangoGrotesque = localFont({
  src: [
    {
      path: "../public/fonts/MangoGrotesque-Regular.woff",
      weight: "400",
      style: "normal",
    }
  ],
  variable: "--font-mango",
});


export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${mangoGrotesque.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* --------------------------------------------------
            Smooth Scroll
        -------------------------------------------------- */}

        <SmoothScroll />

        {/* --------------------------------------------------
            Header
        -------------------------------------------------- */}
        

        {/* --------------------------------------------------
            Main Content
        -------------------------------------------------- */}

        <div
          id="smooth-wrapper"
          className="overflow-hidden"
        >
          <div
            id="smooth-content"
            className="will-change-transform"
          >
            <Header />

            {children}

            {/* --------------------------------------------------
                Footer
            -------------------------------------------------- */}

            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
